In [4]:
import io
import os
import requests
import pandas as pd
from google.cloud import storage
import urllib.request
import pyarrow

In [5]:
# services = ['fhv','green','yellow']
init_url = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/fhv/'

# switch out the bucketname
BUCKET = os.environ.get("GCP_GCS_BUCKET", "dtc_data_lake_ny-rides-kelvin")

In [3]:
def upload_to_gcs(bucket, object_name, local_file):
    """
    Ref: https://cloud.google.com/storage/docs/uploading-objects#storage-upload-object-python
    """
    # # WORKAROUND to prevent timeout for files > 6 MB on 800 kbps upload speed.
    # # (Ref: https://github.com/googleapis/python-storage/issues/74)
    # storage.blob._MAX_MULTIPART_SIZE = 5 * 1024 * 1024  # 5 MB
    # storage.blob._DEFAULT_CHUNKSIZE = 5 * 1024 * 1024  # 5 MB

    client = storage.Client()
    bucket = client.bucket(bucket)
    blob = bucket.blob(object_name)
    blob.upload_from_filename(local_file)

In [ ]:
def web_to_gcs(year, service):
    for i in range(12):
        i = i + 1
        
        # sets the month part of the file_name string
        month = '0'+str(i+1)
        month = month[-2:]

        # csv.gz  file_name 
        file_name = service + '_tripdata_' + year + '-' + month + '.csv.gz'
        
        # download csv.gz file
        request_url = init_url + file_name
        urllib.request.urlretrieve(request_url, '../homework/data/' + file_name)

        df = pd.read_csv('../homework/data/' + file_name, encoding='latin1')
        file_name = file_name.replace('.csv.gz', '.parquet')
        df.to_parquet('../homework/data/' + file_name, engine='pyarrow')
        print(f"Parquet: {file_name}")

        # upload it to gcs 
        upload_to_gcs(BUCKET, f"{service}_parquet/{file_name}", '../homework/data/' + file_name)
        print(f"GCS: {service}_parquet/{file_name}")


# web_to_gcs('2019', 'green')
# web_to_gcs('2020', 'green')
# web_to_gcs('2019', 'yellow')
# web_to_gcs('2020', 'yellow')
# web_to_gcs('2019', 'fhv')
web_to_gcs('2020', 'fhv')
# web_to_gcs('2021', 'fhv')

In [18]:
file_name = 'fhv' + '_tripdata_' + '2020' + '-' + '02' + '.parquet'
df = pd.read_parquet('../homework/data/' + file_name)
df.shape[0]
df.tail(100)

,dispatching_base_num,pickup_datetime,dropoff_datetime,PULocationID,DOLocationID,SR_Flag,Affiliated_base_number
1910057,B03060,2020-02-29 23:49:05,2020-03-01 00:08:28,264.0,188.0,NaN,B02887
1910058,B03060,2020-02-29 23:22:39,2020-02-29 23:36:26,264.0,106.0,NaN,B03060
1910059,B03060,2020-02-29 23:07:59,2020-02-29 23:40:18,264.0,17.0,NaN,B02765
1910060,B03060,2020-02-29 23:08:06,2020-02-29 23:16:53,264.0,22.0,NaN,B02882
1910061,B03060,2020-02-29 23:28:16,2020-02-29 23:43:03,264.0,155.0,NaN,B02882
...,...,...,...,...,...,...,...
1910152,B03284,2020-02-29 23:12:03,2020-03-01 00:38:01,48.0,39.0,NaN,None
1910153,B03284,2020-02-29 23:30:44,2020-02-29 23:34:27,71.0,71.0,NaN,None
1910154,B03284,2020-02-29 23:39:55,2020-02-29 23:44:03,71.0,71.0,NaN,None
1910155,B03284,2020-02-29 23:22:23,2020-02-29 23:51:03,197.0,22.0,NaN,None
1910156,B03284,2020-02-29 23:08:41,2020-02-29 23:29:02,41.0,168.0,NaN,None